/*
 * ptruora
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0a0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainParameters struct {
	ServerChange bool `json:"server_change,omitempty"`

	SslGrade string `json:"ssl_grade,omitempty"`

	PreviusSslGrade string `json:"previus_ssl_grade,omitempty"`

	Logo string `json:"logo,omitempty"`

	Title string `json:"title,omitempty"`

	IsDown bool `json:"is_down,omitempty"`

	Name string `json:"name,omitempty"`

	Servers []ServerParameters `json:"servers,omitempty"`
}
