/*
 * ptruora
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0a0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServerParameters struct {
	Address string `json:"address,omitempty"`

	SslGrade string `json:"ssl_grade,omitempty"`

	Country string `json:"country,omitempty"`

	Owner string `json:"owner,omitempty"`
}

func endpointsToServerParameters(ep Endpoints) ServerParameters {
	return ServerParameters{ep.IPAddress, ep.Grade, "", ""}
}
